name: Containers

on:
  push:
    branches:
      - 'master'
    tags:
      - dnscache-v*
      - uploader-v*

jobs:
  dnscache:
    name: Deploy Docker Image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Publish Docker Image
        uses: rgaudin/openzim-docker-action@main
        with:
          image-path: openzim/dnscache
          on-master: latest
          tag-pattern: dnscache-v*
          restrict-to: openzim/zimfarm
          context: dnscache
          hub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          hub-password: ${{ secrets.DOCKERHUB_PASSWORD }}
          ghcr-username: ${{ secrets.GHCR_USERNAME }}
          ghcr-token: ${{ secrets.GHCR_TOKEN }}

  uploader:
    name: Deploy Docker Image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Publish Docker Image
        uses: rgaudin/openzim-docker-action@main
        with:
          image-path: openzim/uploader
          on-master: latest
          tag-pattern: uploader-v*
          restrict-to: openzim/zimfarm
          context: uploader
          hub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          hub-password: ${{ secrets.DOCKERHUB_PASSWORD }}
          ghcr-username: ${{ secrets.GHCR_USERNAME }}
          ghcr-token: ${{ secrets.GHCR_TOKEN }}

  dispatcher:
    name: Deploy Docker Image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Publish Docker Image
        uses: rgaudin/openzim-docker-action@main
        with:
          image-path: openzim/zimfarm-dispatcher
          on-master: latest
          restrict-to: openzim/zimfarm
          context: dispatcher/backend
          hub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          hub-password: ${{ secrets.DOCKERHUB_PASSWORD }}
          ghcr-username: ${{ secrets.GHCR_USERNAME }}
          ghcr-token: ${{ secrets.GHCR_TOKEN }}

  ui:
    name: Deploy Docker Image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Publish Docker Image
        uses: rgaudin/openzim-docker-action@main
        with:
          image-path: openzim/zimfarm-ui
          on-master: latest
          restrict-to: openzim/zimfarm
          context: dispatcher/frontend-ui
          hub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          hub-password: ${{ secrets.DOCKERHUB_PASSWORD }}
          ghcr-username: ${{ secrets.GHCR_USERNAME }}
          ghcr-token: ${{ secrets.GHCR_TOKEN }}

  receiver:
    name: Deploy Docker Image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Publish Docker Image
        uses: rgaudin/openzim-docker-action@main
        with:
          image-path: openzim/zimfarm-receiver
          on-master: latest
          restrict-to: openzim/zimfarm
          context: receiver
          hub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          hub-password: ${{ secrets.DOCKERHUB_PASSWORD }}
          ghcr-username: ${{ secrets.GHCR_USERNAME }}
          ghcr-token: ${{ secrets.GHCR_TOKEN }}

  task-worker:
    name: Deploy Docker Image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Publish Docker Image
        uses: rgaudin/openzim-docker-action@main
        with:
          image-path: openzim/zimfarm-task-worker
          on-master: latest
          restrict-to: openzim/zimfarm
          context: workers
          dockerfile: task-Dockerfile
          hub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          hub-password: ${{ secrets.DOCKERHUB_PASSWORD }}
          ghcr-username: ${{ secrets.GHCR_USERNAME }}
          ghcr-token: ${{ secrets.GHCR_TOKEN }}

  worker-manager:
    name: Deploy Docker Image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Publish Docker Image
        uses: rgaudin/openzim-docker-action@main
        with:
          image-path: openzim/zimfarm-worker-manager
          on-master: latest
          restrict-to: openzim/zimfarm
          context: workers
          dockerfile: manager-Dockerfile
          hub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          hub-password: ${{ secrets.DOCKERHUB_PASSWORD }}
          ghcr-username: ${{ secrets.GHCR_USERNAME }}
          ghcr-token: ${{ secrets.GHCR_TOKEN }}
