name: Docker

on:
  push:
    branches:
      - 'master'
    tags:
      - dnscache-v*
      - uploader-v*

jobs:
  dnscache:
    name: Deploy dnscache Image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Publish Docker Image
        uses: openzim/docker-publish-action@v1
        with:
          image-path: openzim/dnscache
          on-master: latest
          tag-pattern: /^dnscache-v([0-9.]+)$/
          restrict-to: openzim/zimfarm
          context: dnscache
          hub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          hub-password: ${{ secrets.DOCKERHUB_PASSWORD }}
          ghcr-username: ${{ secrets.GHCR_USERNAME }}
          ghcr-token: ${{ secrets.GHCR_TOKEN }}

  uploader:
    name: Deploy uploader Image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Publish Docker Image
        uses: openzim/docker-publish-action@v1
        with:
          image-path: openzim/uploader
          on-master: latest
          tag-pattern: /^uploader-v([0-9.]+)$/
          restrict-to: openzim/zimfarm
          context: uploader
          hub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          hub-password: ${{ secrets.DOCKERHUB_PASSWORD }}
          ghcr-username: ${{ secrets.GHCR_USERNAME }}
          ghcr-token: ${{ secrets.GHCR_TOKEN }}

  dispatcher:
    name: Deploy dispatcher Image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Publish Docker Image
        uses: openzim/docker-publish-action@v1
        with:
          image-path: openzim/zimfarm-dispatcher
          on-master: latest
          restrict-to: openzim/zimfarm
          context: dispatcher/backend
          hub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          hub-password: ${{ secrets.DOCKERHUB_PASSWORD }}
          ghcr-username: ${{ secrets.GHCR_USERNAME }}
          ghcr-token: ${{ secrets.GHCR_TOKEN }}

  ui:
    name: Deploy ui Image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Publish Docker Image
        uses: openzim/docker-publish-action@v1
        with:
          image-path: openzim/zimfarm-ui
          on-master: latest
          restrict-to: openzim/zimfarm
          context: dispatcher/frontend-ui
          hub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          hub-password: ${{ secrets.DOCKERHUB_PASSWORD }}
          ghcr-username: ${{ secrets.GHCR_USERNAME }}
          ghcr-token: ${{ secrets.GHCR_TOKEN }}

  receiver:
    name: Deploy receiver Image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Publish Docker Image
        uses: openzim/docker-publish-action@v1
        with:
          image-path: openzim/zimfarm-receiver
          on-master: latest
          restrict-to: openzim/zimfarm
          context: receiver
          hub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          hub-password: ${{ secrets.DOCKERHUB_PASSWORD }}
          ghcr-username: ${{ secrets.GHCR_USERNAME }}
          ghcr-token: ${{ secrets.GHCR_TOKEN }}

  task-worker:
    name: Deploy task-worker Image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Publish Docker Image
        uses: openzim/docker-publish-action@v1
        with:
          image-path: openzim/zimfarm-task-worker
          on-master: latest
          restrict-to: openzim/zimfarm
          context: workers
          dockerfile: task-Dockerfile
          hub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          hub-password: ${{ secrets.DOCKERHUB_PASSWORD }}
          ghcr-username: ${{ secrets.GHCR_USERNAME }}
          ghcr-token: ${{ secrets.GHCR_TOKEN }}

  worker-manager:
    name: Deploy worker-manager Image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Publish Docker Image
        uses: openzim/docker-publish-action@v1
        with:
          image-path: openzim/zimfarm-worker-manager
          on-master: latest
          restrict-to: openzim/zimfarm
          context: workers
          dockerfile: manager-Dockerfile
          hub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          hub-password: ${{ secrets.DOCKERHUB_PASSWORD }}
          ghcr-username: ${{ secrets.GHCR_USERNAME }}
          ghcr-token: ${{ secrets.GHCR_TOKEN }}
