name: Docker

on:
  push:
    branches:
      - 'main'
    tags:
      - dnscache-v*
      - uploader-v*

jobs:
  dnscache:
    name: Deploy dnscache Image
    runs-on: ubuntu-22.04
    steps:
      - name: Retrieve source code
        uses: actions/checkout@v3.4.0

      - name: Publish Docker Image
        uses: openzim/docker-publish-action@v10
        with:
          image-name: openzim/dnscache
          on-master: latest
          tag-pattern: /^dnscache-v([0-9.]+)$/
          restrict-to: openzim/zimfarm
          context: dnscache
          registries: ghcr.io
          credentials:
            GHCRIO_USERNAME=${{ secrets.GHCR_USERNAME }}
            GHCRIO_TOKEN=${{ secrets.GHCR_TOKEN }}

  uploader:
    name: Deploy uploader Image
    runs-on: ubuntu-22.04
    steps:
      - name: Retrieve source code
        uses: actions/checkout@v3.4.0

      - name: Publish Docker Image
        uses: openzim/docker-publish-action@v10
        with:
          image-name: openzim/uploader
          on-master: latest
          tag-pattern: /^uploader-v([0-9.]+)$/
          restrict-to: openzim/zimfarm
          context: uploader
          registries: ghcr.io
          credentials:
            GHCRIO_USERNAME=${{ secrets.GHCR_USERNAME }}
            GHCRIO_TOKEN=${{ secrets.GHCR_TOKEN }}

  dispatcher:
    name: Deploy dispatcher Image
    runs-on: ubuntu-22.04
    steps:
      - name: Retrieve source code
        uses: actions/checkout@v3.4.0

      - name: Publish Docker Image
        uses: openzim/docker-publish-action@v10
        with:
          image-name: openzim/zimfarm-dispatcher
          on-master: latest
          restrict-to: openzim/zimfarm
          context: dispatcher/backend
          registries: ghcr.io
          credentials:
            GHCRIO_USERNAME=${{ secrets.GHCR_USERNAME }}
            GHCRIO_TOKEN=${{ secrets.GHCR_TOKEN }}

  ui:
    name: Deploy ui Image
    runs-on: ubuntu-22.04
    steps:
      - name: Retrieve source code
        uses: actions/checkout@v3.4.0

      - name: Publish Docker Image
        uses: openzim/docker-publish-action@v10
        with:
          image-name: openzim/zimfarm-ui
          on-master: latest
          restrict-to: openzim/zimfarm
          context: dispatcher/frontend-ui
          registries: ghcr.io
          credentials:
            GHCRIO_USERNAME=${{ secrets.GHCR_USERNAME }}
            GHCRIO_TOKEN=${{ secrets.GHCR_TOKEN }}

  receiver:
    name: Deploy receiver Image
    runs-on: ubuntu-22.04
    steps:
      - name: Retrieve source code
        uses: actions/checkout@v3.4.0

      - name: Publish Docker Image
        uses: openzim/docker-publish-action@v10
        with:
          image-name: openzim/zimfarm-receiver
          on-master: latest
          restrict-to: openzim/zimfarm
          context: receiver
          registries: ghcr.io
          credentials:
            GHCRIO_USERNAME=${{ secrets.GHCR_USERNAME }}
            GHCRIO_TOKEN=${{ secrets.GHCR_TOKEN }}

  task-worker:
    name: Deploy task-worker Image
    runs-on: ubuntu-22.04
    steps:
      - name: Retrieve source code
        uses: actions/checkout@v3.4.0

      - name: Publish Docker Image
        uses: openzim/docker-publish-action@v10
        with:
          image-name: openzim/zimfarm-task-worker
          on-master: latest
          restrict-to: openzim/zimfarm
          context: workers
          dockerfile: task-Dockerfile
          registries: ghcr.io
          credentials:
            GHCRIO_USERNAME=${{ secrets.GHCR_USERNAME }}
            GHCRIO_TOKEN=${{ secrets.GHCR_TOKEN }}

  worker-manager:
    name: Deploy worker-manager Image
    runs-on: ubuntu-22.04
    steps:
      - name: Retrieve source code
        uses: actions/checkout@v3.4.0

      - name: Publish Docker Image
        uses: openzim/docker-publish-action@v10
        with:
          image-name: openzim/zimfarm-worker-manager
          on-master: latest
          restrict-to: openzim/zimfarm
          context: workers
          dockerfile: manager-Dockerfile
          registries: ghcr.io
          credentials:
            GHCRIO_USERNAME=${{ secrets.GHCR_USERNAME }}
            GHCRIO_TOKEN=${{ secrets.GHCR_TOKEN }}

  monitor:
    name: Deploy monitor Image
    runs-on: ubuntu-22.04
    steps:
      - name: Retrieve source code
        uses: actions/checkout@v3.4.0

      - name: Publish Docker Image
        uses: openzim/docker-publish-action@v10
        with:
          image-name: openzim/zimfarm-monitor
          on-master: latest
          restrict-to: openzim/zimfarm
          context: monitor
          registries: ghcr.io
          credentials:
            GHCRIO_USERNAME=${{ secrets.GHCR_USERNAME }}
            GHCRIO_TOKEN=${{ secrets.GHCR_TOKEN }}

  watcher:
    name: Deploy watcher Image
    runs-on: ubuntu-22.04
    steps:
      - name: Retrieve source code
        uses: actions/checkout@v3.4.0

      - name: Publish Docker Image
        uses: openzim/docker-publish-action@v10
        with:
          image-name: openzim/zimfarm-watcher
          on-master: latest
          restrict-to: openzim/zimfarm
          context: watcher
          registries: ghcr.io
          credentials:
            GHCRIO_USERNAME=${{ secrets.GHCR_USERNAME }}
            GHCRIO_TOKEN=${{ secrets.GHCR_TOKEN }}
